# Generated by Django 4.2.3 on 2023-07-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_answer_direction_answer_downvotes_answer_upvotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='dest_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='source_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
